import { useMemo } from 'react';

interface UseNewItemStylesProps {
  isMobile: boolean;
  isTablet: boolean;
  dragActive: boolean;
}

export const useNewItemStyles = ({ isMobile, isTablet, dragActive }: UseNewItemStylesProps) => {
  return useMemo(() => ({
    container: {
      background: 'linear-gradient(135deg, #f8fafc 0%, #e2e8f0 25%, #f1f5f9 100%)',
      minHeight: '100%',
      padding: isMobile ? '1rem' : isTablet ? '1.5rem' : '2rem',
    },
    header: {
      display: 'flex',
      alignItems: 'center',
      gap: '1rem',
      marginBottom: '2rem',
    },
    backButton: {
      display: 'flex',
      alignItems: 'center',
      gap: '0.5rem',
      padding: '0.75rem 1.25rem',
      background: 'white',
      border: '1px solid #e2e8f0',
      borderRadius: '12px',
      color: '#64748b',
      cursor: 'pointer',
      transition: 'all 0.3s ease',
      fontSize: '0.95rem',
      fontWeight: '500',
    },
    title: {
      fontSize: isMobile ? '1.75rem' : '2.25rem',
      fontWeight: 'bold',
      color: '#1e293b',
      margin: 0,
    },
    subtitle: {
      fontSize: '1.1rem',
      color: '#64748b',
      margin: '0.5rem 0 0',
    },
    mainContent: {
      display: 'grid',
      gridTemplateColumns: isMobile ? '1fr' : isTablet ? '1fr' : '1fr 400px',
      gap: '2rem',
      maxWidth: '1200px',
      margin: '0 auto',
    },
    uploadSection: {
      background: 'white',
      borderRadius: '24px',
      padding: isMobile ? '1.5rem' : '2rem',
      boxShadow: '0 4px 20px rgba(0, 0, 0, 0.05)',
      border: '1px solid rgba(226, 232, 240, 0.5)',
    },
    sectionTitle: {
      fontSize: '1.25rem',
      fontWeight: 'bold',
      color: '#1e293b',
      marginBottom: '1.5rem',
      display: 'flex',
      alignItems: 'center',
      gap: '0.5rem',
    },
    dropZone: {
      border: `2px dashed ${dragActive ? '#667eea' : '#cbd5e1'}`,
      borderRadius: '16px',
      padding: '3rem 2rem',
      textAlign: 'center' as const,
      background: dragActive ? 'rgba(102, 126, 234, 0.05)' : 'linear-gradient(135deg, #f8fafc 0%, #e2e8f0 100%)',
      transition: 'all 0.3s ease',
      cursor: 'pointer',
      position: 'relative' as const,
    },
    dropZoneActive: {
      borderColor: '#667eea',
      background: 'rgba(102, 126, 234, 0.05)',
      transform: 'scale(1.02)',
    },
    uploadIcon: {
      width: '64px',
      height: '64px',
      background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
      borderRadius: '16px',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      margin: '0 auto 1rem',
      boxShadow: '0 8px 20px rgba(102, 126, 234, 0.3)',
    },
    uploadText: {
      fontSize: '1.1rem',
      fontWeight: '600',
      color: '#1e293b',
      marginBottom: '0.5rem',
    },
    uploadSubtext: {
      fontSize: '0.9rem',
      color: '#64748b',
      marginBottom: '1.5rem',
    },
    selectButton: {
      padding: '0.75rem 1.5rem',
      background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
      border: 'none',
      borderRadius: '12px',
      color: 'white',
      fontWeight: '600',
      cursor: 'pointer',
      transition: 'all 0.3s ease',
      fontSize: '0.95rem',
    },
    hiddenInput: {
      display: 'none',
    },
    imagePreview: {
      marginTop: '1.5rem',
      textAlign: 'center' as const,
    },
    previewImage: {
      maxWidth: '100%',
      maxHeight: '300px',
      borderRadius: '12px',
      boxShadow: '0 8px 25px rgba(0, 0, 0, 0.1)',
      marginBottom: '1rem',
    },
    imageActions: {
      display: 'flex',
      gap: '1rem',
      justifyContent: 'center',
      flexWrap: 'wrap' as const,
    },
    actionButton: {
      padding: '0.75rem 1.25rem',
      borderRadius: '12px',
      border: 'none',
      cursor: 'pointer',
      fontWeight: '600',
      transition: 'all 0.3s ease',
      display: 'flex',
      alignItems: 'center',
      gap: '0.5rem',
      fontSize: '0.9rem',
    },
    changeButton: {
      background: '#f1f5f9',
      color: '#64748b',
      border: '1px solid #e2e8f0',
    },
    saveButton: {
      background: 'linear-gradient(135deg, #10b981 0%, #059669 100%)',
      color: 'white',
      boxShadow: '0 4px 15px rgba(16, 185, 129, 0.3)',
    },
    detailsSection: {
      background: 'white',
      borderRadius: '24px',
      padding: isMobile ? '1.5rem' : '2rem',
      boxShadow: '0 4px 20px rgba(0, 0, 0, 0.05)',
      border: '1px solid rgba(226, 232, 240, 0.5)',
      height: 'fit-content',
    },
    formGroup: {
      marginBottom: '1.5rem',
    },
    label: {
      display: 'block',
      fontSize: '0.9rem',
      fontWeight: '600',
      color: '#374151',
      marginBottom: '0.5rem',
    },
    input: {
      width: '100%',
      padding: '0.75rem',
      border: '1px solid #d1d5db',
      borderRadius: '8px',
      fontSize: '0.95rem',
      transition: 'border-color 0.2s ease',
      outline: 'none',
      boxSizing: 'border-box' as const,
    },
    select: {
      width: '100%',
      padding: '0.75rem',
      border: '1px solid #d1d5db',
      borderRadius: '8px',
      fontSize: '0.95rem',
      transition: 'border-color 0.2s ease',
      outline: 'none',
      background: 'white',
      boxSizing: 'border-box' as const,
    },
    textarea: {
      width: '100%',
      padding: '0.75rem',
      border: '1px solid #d1d5db',
      borderRadius: '8px',
      fontSize: '0.95rem',
      transition: 'border-color 0.2s ease',
      outline: 'none',
      resize: 'vertical' as const,
      minHeight: '80px',
      boxSizing: 'border-box' as const,
    },
    successModal: {
      position: 'fixed' as const,
      top: 0,
      left: 0,
      width: '100vw',
      height: '100vh',
      background: 'rgba(0, 0, 0, 0.5)',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      zIndex: 9999,
    },
    successContent: {
      background: 'white',
      borderRadius: '20px',
      padding: '3rem 2rem',
      textAlign: 'center' as const,
      maxWidth: '400px',
      margin: '1rem',
      boxShadow: '0 20px 40px rgba(0, 0, 0, 0.1)',
    },
    successIcon: {
      width: '80px',
      height: '80px',
      background: 'linear-gradient(135deg, #10b981 0%, #059669 100%)',
      borderRadius: '50%',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      margin: '0 auto 1.5rem',
      boxShadow: '0 8px 25px rgba(16, 185, 129, 0.3)',
    },
    successTitle: {
      fontSize: '1.5rem',
      fontWeight: 'bold',
      color: '#1e293b',
      marginBottom: '0.5rem',
    },
    successText: {
      color: '#64748b',
      marginBottom: '1.5rem',
    },
    loadingSpinner: {
      width: '20px',
      height: '20px',
      border: '2px solid rgba(255, 255, 255, 0.3)',
      borderTop: '2px solid white',
      borderRadius: '50%',
      animation: 'spin 1s linear infinite',
      marginRight: '0.5rem',
    },
  }), [isMobile, isTablet, dragActive]);
}; 